version: "3.0"
services:
  spring-app-1:
    container_name: springbootshop3
    image: springbootshop:latest
    ports:
      - "8081:8080"

  spring-app-2:
    container_name: springbootshop4
    image: springbootshop:latest
    ports:
      - "8082:8080"

  nginx:
    container_name: nginx-server2
    image: nginx_springboot:latest
    ports:
      - "9600:80"
    depends_on:
      - spring-app-1
      - spring-app-2
