INSERT INTO MEMBER(member_name) VALUES ('test1');
INSERT INTO MEMBER(member_name) VALUES ('test2');
INSERT INTO MEMBER(member_name) VALUES ('test3');
INSERT INTO MEMBER(member_name) VALUES ('test4');

INSERT INTO ITEM(ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('쓱배송', '허쉬 초코멜로쿠키 45g', 600, 10);
INSERT INTO ITEM(ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('쓱배송', '크리스피롤 12 곡 180g', 2800, 5);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('쓱배송', '동물복지 유정란 15 개입 대란', 4350, 0);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('쓱배송', '말랑카우 핸드워시 250ml', 2600, 6);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('쓱배송', '삼립 미니꿀호떡 322g', 1200, 4);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('새벽배송','피코크 어랑손만두 어랑만두 700g', 6400, 2);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('새벽배송','빼빼로바 아몬드아이스크림 4 입', 2800, 1);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('새벽배송','피코크 에이 클래스 우유 900ml', 2500, 3);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('새벽배송','아삭달콤 방울토마토 500g', 4500 ,0);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('새벽배송','[롯데삼강] 돼지바 (70ml*6 입)', 3000 ,1);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','키즈 피크닉 팩 M', 65000, 4);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','[롯데삼강] 돼지바 (70ml*6 입)', 3000 ,1);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','이달의 원두 500g', 18500, 4);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','아쿠아 머그', 23000, 7);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','삼성전자 43 인치 스마트모니터', 480000, 2);
INSERT INTO ITEM( ITEM_GROUP ,ITEM_NAME ,ITEM_PRICE ,ITEM_QUANTITY ) VALUES ('택배','나이키 헤리티지 스우시 캡', 25000, 5);

INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (1,1,4);
INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (2,1,2);
INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (3,1,2);
INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (4,1,5);
INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (5,1,1);
INSERT INTO CART(ITEM_ID,MEMBER_ID,CART_QUANTITY )  VALUES (6,1,1);

